server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://service-account:8081
          predicates:
            - Path=/user/**

        - id: location-service
          uri: http://sesrvice-bike:8082
          predicates:
            - Path=/bikeLocation/**

        - id: service-bike
          uri: http://service-map:8083
          predicates:
            - Path=/bike/**

        - id: service-payment
          uri: http://service-payment:8084
          predicates:
            - Path=/payment/**