server:
  port: 8082
  error:
    include-message: always

springdoc:

  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:

  application:
    name: location-service
  cloud:
    config:
      import-check:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/location_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springdoc: DEBUG

jwt:
  secret: YourSecureSecretKeyMustBeAtLeast32BytesLong